hfa/urls.py
# coding: utf-8 f
from django.conf.urls import patterns, include, url
from main.views import home, hardwareAbuse
from users.views import error, login, profile, settings, confirmEmail, newEmail, disconnect
from django.contrib import admin
from hardware.views import displayHardware, listHardware, listComponents, hardwareEdit, deleteHardware, sendMail, searchHardware, giveaway, takeback, new_images, history
from hfa.settings import DEBUG, MEDIA_ROOT
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
import allauth
from django.utils import importlib

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
 url(r'^upload/', include('fileupload.urls')),
    url(r'^$', home, name='home'),
    url(r'^users/(?P<userid>.*)$', profile, name='profile'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^hardware/view/(?P<id>.*)/(?P<name>.*)$', displayHardware, name="display hardware"),
    url(r'^hardware/giveaway/$', giveaway),
    url(r'^hardware/takeback/(?P<hardwareid>.*)', takeback),
    url(r'^hardware/new/$', hardwareEdit),
    url(r'^hardware/newimages/(?P<hardwareid>.*)$', new_images),
    url(r'^hardware/history/$', history),
    url(r'^hardware/edit/(?P<id>.*)$', hardwareEdit),
    url(r'^hardware/delete/(?P<id>.*)$', deleteHardware),
    url(r'^hardware/contact/(?P<hardwareid>.*)$', sendMail),
    url(r'^hardware/search/$', searchHardware),
    url(r'^hardware/search/(?P<page>.*)$', searchHardware),
    url(r'^hardware/list/$', listHardware),
    url(r'^hardware/list/components/$', listComponents),
    url(r'^hardware/list/components/(?P<page>\d*)$', listComponents),
    url(r'^hardware/list/(?P<page>\d*)$', listHardware),
    url(r'^hardware/abuse/$', hardwareAbuse),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login),
    url(r'^account/login/cancelled/$', "allauth.socialaccount.views.login_cancelled", name='socialaccount_login_cancelled'),
    url(r'^account/login/error/$', "allauth.socialaccount.views.login_error", name='socialaccount_login_error'),
    url(r"^logout/$", "allauth.account.views.logout", name="account_logout"),
    url(r'^accounts/confirm/(?P<confirmation_key>.*)$', confirmEmail),
    url(r'^accounts/newmail$', newEmail),
    url(r'^accounts/disconnect/(?P<socialacc>.*)$', disconnect),
    url(r'^accounts/delete/$', disconnect),
    url(r'^accounts/', include('allauth.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

for provider in allauth.socialaccount.providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += patterns('', url(r'^accounts/', include(prov_urlpatterns)))

if DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^images/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': MEDIA_ROOT}))

hardware/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from main.models import Location
from django.template.defaultfilters import slugify
from hfa.util import get_hfile_name, get_cfile_name

lendlengthtypes = (
		('1', 'Tag(e)'),
		('7', 'Woche(n)'),
		('30', 'Monat(e)'),
		('356', 'Jahr(e)')
)

class Condition(models.Model):
	"""Different conditions such as 'damaged', 'new', 'slightly used'"""
	name = models.CharField(_('name'), max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = _('condition')
		verbose_name_plural = _('condition')

class Category(models.Model):
	"""Categories such as 'smartphone', 'laptop', ..."""
	name = models.CharField(_('name'), max_length=200)
	icon = models.ImageField(upload_to=get_cfile_name)
	ready_to_use = models.BooleanField()
	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = _('category')
		verbose_name_plural = _('category')

class State(models.Model):
	"""Whether the owner wants to give the hardware away or lend it"""
	name = models.CharField(_('name'), max_length=200)
	temporary = models.BooleanField()

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = _('state')
		verbose_name_plural = _('state')

class Hardware(models.Model):
	"""The hardware itself"""
	name = models.CharField(_('name'), max_length=200)
	slug = models.SlugField(max_length=200)
	condition = models.ForeignKey(Condition, verbose_name = _('condition'), blank=False)
	category = models.ForeignKey(Category, verbose_name = _('category'), blank=False)
	description = models.TextField(_('description'))
	availability = models.BooleanField(_('availability'), default=True)
	state = models.ForeignKey(State, verbose_name = _('state'), blank=False)
	owner = models.ForeignKey(User, verbose_name = _('owner'), related_name='hardware_owner')
	lent_to = models.ForeignKey(User, verbose_name = _('lent to'), related_name='hardware_lent_to', blank=True, null=True)
	location = models.ForeignKey(Location, verbose_name = _('location'), null=True)
	lendlength = models.IntegerField(null=True, blank=True)
	lendlengthtype = models.IntegerField( null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = _('hardware')
		verbose_name_plural = _('hardware')

	def save(self):
		self.slug = slugify(self.name)
		super(Hardware, self).save()

class Image(models.Model):
	image = models.ImageField(upload_to=get_hfile_name)
	caption = models.TextField(max_length=400)
	hardware = models.ForeignKey(Hardware)

	@models.permalink
	def get_absolute_url(self):
		return ('upload-new', )

	def save(self, *args, **kwargs):
		self.slug = self.file.namer
		super(Image, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		self.image.delete(False)
		super(Image, self).delete(*args, **kwargs)

class EmailLog(models.Model):
	sender = models.ForeignKey(User, related_name='log_sender')
	hardware = models.ForeignKey(Hardware)
	receiver = models.ForeignKey(User, related_name='log_receiver')
	date = models.DateTimeField(auto_now_add=True)

hardware/forms.py
 # -*- coding: utf-8 -*-
from django import forms
from hardware.models import Condition, Category, State
from django.utils.html import conditional_escape, escape
from django.utils.encoding import force_unicode

lendlengthtypes = (
		('1', 'Tag(e)'),
		('7', 'Woche(n)'),
		('30', 'Monat(e)'),
		('356', 'Jahr(e)')
)

class SelectWithTitles(forms.Select):
	def __init__(self, *args, **kwargs):
		super(SelectWithTitles, self).__init__(*args, **kwargs)

		self.titles = {}

	def render_option(self, selected_choices, option_value, option_label):
		title_html = (option_label in self.titles) and \
			u' title="%s" ' % escape(force_unicode(self.titles[option_label])) or ''
		option_value = force_unicode(option_value)
		selected_html = (option_value in selected_choices) and u' selected="selected"' or ''
		return u'<option value="%s"%s%s>%s</option>' % (
			escape(option_value), title_html, selected_html,
			conditional_escape(force_unicode(option_label)))
pty_label=None
class ChoiceFieldWithTitles(forms.ChoiceField):
	widget = SelectWithTitles(attrs={"class":"span2", 'title':"Brauchst du das Gerät irgendwann wieder oder hast du selbst gar keine Verwendung mehr dafür?"})

	def __init__(self, choices=(), *args, **kwargs):
		choice_pairs = [(c[0], c[1]) for c in choices]
		super(ChoiceFieldWithTitles, self).__init__(choices=choice_pairs, *args, **kwargs)
		self.widget.titles = dict([(c[1], c[2]) for c in choices])

class HardwareForm(forms.Form):
	error_css_class = 'error'
	namewidget=forms.TextInput(attrs={"class":"span3", 'title':"Gib den Namen deiner Hardware ein, am Besten einfach die Produktbezeichnung."})
	name = forms.CharField(max_length=200, widget=namewidget)
	descriptionwidget=forms.Textarea(attrs={"class":"span6", "rows":15, 'title':"Beschreibe deine Hardware: welche Macken und Eigenheiten erwarten einen neuen Besitzer eventuell? Was für Besonderheiten hat deine Hardware?"})
	description = forms.CharField(widget=descriptionwidget)
	conditionwidget=forms.Select(attrs={"class":"span2", 'title':"Wähle den Zustand ehrlich aus; du musst nichts besser ausgeben als es ist."})
	condition = forms.ModelChoiceField(queryset=Condition.objects.all(), empty_label=None, widget=conditionwidget)
	categorywidget=forms.Select(attrs={"class":"span2", 'title':"Wähle aus um was für ein Gerät es sich handelt."})
	category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label=None, widget=categorywidget)
	state = ChoiceFieldWithTitles()
	lendlengthwidget=forms.TextInput(attrs={"class":"span1", 'title':"Schätze ab, wann du das Gerät spätestens selbst wieder benötigen wirst."})
	lendlength = forms.IntegerField(required=False, widget=lendlengthwidget)
	lendlengthtypewidget = forms.Select(attrs={"class":"span2"})
	lendlengthtype = forms.ChoiceField(choices=lendlengthtypes, required=False, widget=lendlengthtypewidget)
	locationwidget=forms.CheckboxInput(attrs={'title':"Wo kann das Gerät abgeholt werden? Wenn du keinen Haken setzt wird einfach der Ort verwendet, den du in deinem Profil angegeben hast."})
	ownlocation = forms.BooleanField(required=False, widget=locationwidget)
	city = forms.CharField(max_length=200, required=False)
	postcode = forms.CharField(max_length=5, required=False)
	street = forms.CharField(max_length=200, required=False)


	def __init__(self, *args, **kwargs):
		super(HardwareForm, self).__init__(*args, **kwargs)

		choices = []
		for c in State.objects.all():
			choices.append((c.id, c.name, c.temporary))
		self.fields['state'] = ChoiceFieldWithTitles(choices = choices)


class SendmailForm(forms.Form):
	text = forms.CharField(widget=forms.Textarea(attrs={"class":"span6"}))
	usage = forms.CharField(widget=forms.Textarea(attrs={"class":"span6", "rows":"5"}), max_length=400)

class SimpleSearchForm(forms.Form):
	searchquery = forms.CharField(required=False)

class SearchForm(SimpleSearchForm):
	SORT_BY_CHOICES = (
		("", "Sortiere nach"),
		("name", "Name"),
		("owner", "Besitzer"),
		("condition", "Zustand"),
		("category", "Kategorie"),
		("state", "Art"),
		("distance", "Entfernung")
	)
	error_css_class = 'error'

	condition = forms.ModelChoiceField(queryset=Condition.objects.all(), empty_label="Zustand", required=False, widget=forms.Select(attrs={"class":"input-medium",}))
	category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Kategorie", required=False, widget=forms.Select(attrs={"class":"input-medium",}))
	state = forms.ModelChoiceField(queryset=State.objects.all(), empty_label="Art", required=False, widget=forms.Select(attrs={"class":"input-medium",}))
	sortby = forms.ChoiceField(choices=SORT_BY_CHOICES, required=False, widget=forms.Select(attrs={"class":"input-medium",}))

class LendForm(forms.Form):
	username = forms.CharField(required=False)

templates/hardware/giveaway.html
{% extends "base.html" %}

{% block heading %}Hardware verleihen{% endblock %}

{% block content %}
<div class="span12">
<form action="{% url hardware.views.giveaway %}" method="post" class="form-inline">{% csrf_token %}
	<p>Gib bitte den Benutzernamen des/der Benutzers/Benutzerin an, an den/die du den Eintrag verleihen möchtest. Falls die Person dir bereits eine Kontaktmail geschickt hat, taucht der Name in der Autovervollständigung auf.</p>
		<div class="control-group {{form.username.css_classes}}">
		<div class="controls">
			<input id="id_username" type="text" name="username" maxlength="200"  class="typeahead" data-provide="typeahead" data-source="['test', 'test2']"/>
		<span class="help-inline">{{form.username.errors}}</span>
		</div>
		</div>
<input type="hidden" name="hardware" value="{{hardwareid}}">
    <button type="submit" class="btn btn-primary">Verleihen</button>
</form>
</div>
{% endblock %}

templates/hardware/hardwareform.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}
{% load upload_tags %}
{% block heading %}
{% if edit %}<b id="hardwarename">{{hardware.name}}</b> bearbeiten{% else %}Neue Hardware hinzufügen{% endif %}
{% endblock %}



{% block script %}
function checkStreet() {
	if ($("#id_city").val() || $("#id_postcode").val()) {
		$("#id_street").prop('disabled', false);
	} else {
		$("#id_street").val("");
		$("#id_street").prop('disabled', true);
	}
}


checkStreet()
$(function() {
	$("#id_city").keypress(function() {checkStreet()});
	$("#id_postcode").keypress(function() {checkStreet()});
	$("#id_city").change(function() {checkStreet()});
	$("#id_postcode").change(function() {checkStreet()});

	$( "#id_city" ).autocomplete({
		source: function( request, response ) {
			$.ajax({
				url: "http://ws.geonames.org/searchJSON",
				dataType: "jsonp",
				data: {
					featureClass: "P",
					style: "full",
					maxRows: 12,
					country: "DE",
					lang:"de",
					name_startsWith: request.term
				},
				success: function( data ) {
					response( $.map( data.geonames, function( item ) {
						return {
							label: item.name + (item.adminName1 ? ", " + item.adminName1 : ""),
							value: item.name,
							postcode: item.lat
						}
					}));
				}
			});
		},
		minLength: 2,
		select: function( event, ui ) {
			 checkStreet();
		},
		open: function() {
			$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
		},
		close: function() {
			$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
		}
	});
});
$(document).ready(function () {
$('input').tooltip({trigger: 'focus', placement:'right'});
$('textarea').tooltip({trigger: 'focus', placement:'right'});
$('select').tooltip({trigger: 'focus', placement:'right'});
});
{% endblock %}

{% block content %}
<div class="span12">
{% if invalidmail %}
	<p>Du benötigst eine bestätigte Email-Adresse. Trage sie in den Einstellungen ein und bestätige sie über dein Email-Postfach.</p>
{% else %}
	{%if edit%}
	<form action="{% url hardware.views.hardwareEdit hardware.id %}" method="post" class="form-horizontal">{% csrf_token %}
	{% else %}
	<form action="{% url hardware.views.hardwareEdit %}" method="post" class="form-horizontal">{% csrf_token %}
	{%endif %}
		<div class="control-group {{form.name.css_classes}}">
			<label class="control-label" for="id_name">Name</label>
			<div class="controls">
				{{ form.name}}
				<span class="help-inline">{{form.name.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.description.css_classes}}">
			<label class="control-label" for="id_description">Beschreibung</label>
			<div class="controls">
				{{form.description}}
				<span class="help-inline">{{form.description.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.condition.css_classes}}">
			<label class="control-label" for="id_condition">Zustand</label>
			<div class="controls">
				{{form.condition}}
				<span class="help-inline">{{form.condition.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.category.css_classes}}">
			<label class="control-label" for="id_category">Kategorie</label>
			<div class="controls">
				{{form.category}}
				<span class="help-inline">{{form.category.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.state.css_classes}}">
			<label class="control-label" for="id_state">Art</label>
			<div class="controls">
				{{form.state}}
				<span class="help-inline">{{form.state.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.lendlength.css_classes}}" id="lendlength_tag">
			<label class="control-label" for="id_lendlength">Leihdauer</label>
			<div class="controls">
				{{form.lendlength}} {{form.lendlengthtype}}
				<span class="help-inline">{{form.lendlength.errors}}</span>
				<span class="help-inline">{{form.lendlengthtype.errors}}</span>
			</div>
		</div>
		<div class="control-group {{form.ownlocation.css_classes}}">
			<label class="control-label" for="id_ownlocation">Eigener Ort</label>
			<div class="controls">
				{{form.ownlocation}}
				<span class="help-inline">{{form.ownlocation.errors}}</span>
			</div>
		</div>
		<div id="locationform" style="display:none">
		<div class="control-group location {{form.city.css_classes}}">
			<label class="control-label" for="id_city">Stadt</label>
			<div class="controls">
				{{form.city}}
				<span class="help-inline">{{form.city.errors}}</span>
			</div>
		</div>
		<div class="control-group location {{form.postcode.css_classes}}">
			<label class="control-label" for="id_postcode">Postleitzahl</label>
			<div class="controls">
				{{form.postcode}}
				<span class="help-inline">{{form.postcode.errors}}</span>
			</div>
		</div>
		<div class="control-group location {{form.street.css_classes}}">
			<label class="control-label" for="id_street">Straße</label>
			<div class="controls">
				{{form.street}}
				<span class="help-inline">{{form.street.errors}}</span>
			</div>
		</div>
		</div>

	{% if edit %}
		<a href="{% url hardware.views.displayHardware hardware.id hardware.slug %}" class="btn">Abbrechen</a>
	{% else %}
		<a href="{% url main.views.home %}"  class="btn btn-normal">Abbrechen</a>
	{% endif %}
	<input type="submit" value="{% if edit %}Bearbeiten{% else %}Einstellen{% endif %}" class="btn btn-primary" />
	</form>
	<script type="text/javascript">
	function toggleLendlength() {
		if($("#id_state").find("option:selected").attr("title") == "True") {
			$("#lendlength_tag").slideDown("fast");
		} else {
			$("#lendlength_tag").slideUp("fast");
		}
	}

	function toggleLocation() {
		if($("#id_ownlocation").attr('checked')) {
			$("#locationform").slideDown("fast");
		} else {
			$("#locationform").slideUp("fast");
		}
	}

	toggleLendlength();
	toggleLocation();

	$("#id_state").change(function() {
		toggleLendlength();
	});

	$("#id_ownlocation").change(function() {
		toggleLocation();
	});

	$("#id_name").keyup(function(event) {
		$("#hardwarename").html($("#id_name").val());
	});
	</script>
	<div class="container">
{% if edit %}
    <form id="fileupload" method="post" action="{% url fileupload.views.multiuploader %}" enctype="multipart/form-data">{% csrf_token %}
    	<input type="hidden" name="hardwareid" value="{{hardware.id}}" id="hardwareid">
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <span class="btn btn-primary fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Dateien hinzufügen…</span>
                    <input type="file" name="file" multiple>
                </span>
                <button type="submit" class="btn btn-success start">
                    <i class="icon-upload icon-white"></i>
                    <span>Upload beginnen</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Upload abbrechen</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>Dateien löschen</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5 fileupload-progress fade">
                <div class="progress progress-success progres-striped active">
                    <div class="bar" style="width:0%"></div>
                </div>
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <div class="fileupload-loading"></div>
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
    </form>
    <div class="fileupload-content">
        <table class="files"></table>
        <div class="fileupload-progressbar"></div>
    </div>
</div>
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade" data-filter=":odd">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Herunterladen</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Vorheriges</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Nächstes</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>
{% upload_js %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/static/js/jquery.ui.widget.js"></script>
<script src="/static/js/tmpl.min.js"></script>
<script src="/static/js/load-image.min.js"></script>
<script src="/static/js/canvas-to-blob.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/bootstrap-image-gallery.min.js"></script>
<script src="/static/js/jquery.iframe-transport.js"></script>
<script src="/static/js/jquery.fileupload.js"></script>
<script src="/static/js/jquery.fileupload-fp.js"></script>
<script src="/static/js/jquery.fileupload-ui.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/main.js"></script>
<script src="/static/js/csrf.js"></script>
{% endif %}
{% endif %}
</div>
{% endblock %}

templates/hardware/hardwarelisttable.html
{% load locationtags %}

{% if hardware %}
<span>Ergebnisse {{hardware.start_index}} bis {{ hardware.end_index}} von {{itemcount}}</span>
<table class="table table-bordered table-striped">
  <tr><th>Name</th><th>Kategorie</th><th>Zustand</th><th>Besitzer</th><th>Ort</th><th>Entfernung</th></tr>

{% for h in hardware %}
  <tr><td><a href="{% url hardware.views.displayHardware h.id h.slug %}">{{h.name}}</a></td>
     <td><img src="/images/{{h.category.icon}}" style="margin-right:8px" />{{h.category}}</td>
    <td>{{h.condition}}</td>
    <td><a href="{% url users.views.profile h.owner.id %}">{{h.owner.get_profile.displayname}}</a></td>
     {% if user.is_authenticated and h.owner.get_profile.displayLocation%}<td>{{h.location.city}}</td>
     <td>{% get_distance h.location user.get_profile.location %}</td>
     {% else %}
     <td>-</td><td>-</td>
     {% endif %}
 </tr>
{% endfor %}
</table>
{% if hardware.has_other_pages %}
{% if search %}
	{% include "hardware/searchpagination.html" %}
{% else %}
	{% include "hardware/pagination.html" %}
{% endif %}
{% endif %}
{% else %}
<p>Es konnten keine Ergebnisse gefunden werden.</p>
{% endif %}

templates/hardware/requestmail.html
Der/Die Benutzer*in {{user}} ist an etwas interessiert, das du bei Hardware für alle angeboten hast.
Es handelt sich dabei um das folgende: {{hardware}}

Informationen zu der Person:

Hardware für alle: http://hardware-fuer-alle.de{% url users.views.profile user.id %}
{% for account in accountlist %}
{{account.provider}}: {{account.get_profile_url}}
{% endfor %}

Er/Sie hat dir die folgende Nachricht geschickt:

{{text}}


Als Grund für die Benutzung hat der/die Benutzer*in+

{{usage}}

templates/hardware/sendmail.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}

{% block heading %}
Besitzer per Email kontaktieren
{% endblock %}

{% block content %}


<div class="span12">
{% if invalidmail %}
	<p>Etwas stimmt mit deiner E-Mail-Adresse nicht. Bist du sicher, das du sie korrekt eingetragen hast?</p>
{% elif ownhardware %}
	<p>Du kannst dich nicht selbst kontaktieren!</p>
{% else %}
<div class="alert alert-block">
  <h4>Achtung!</h4>
  Damit dein Gegenüber weiß mit wem er schreibt, wird die E-Mail, die an den Hardwarebesitzer verschickt wird, die folgenden Informationen beinhalten:
<ul>
	<li>Deine E-Mailadresse, die du in den Einstellungen angegeben hast.</li>
	<li>Ein Link zu deinem Profil bei "Hardware für Alle".</li>
	<li>Links zu deinen Profilen bei den sozialen Netzwerken, die du in den Einstellungen verknüpft hast.</li>
</ul>
Du schreibst dem Anbieter der Hardware direkt. Die Nachricht und das Angebot sind unverbindlich. Stelle dem Anbieter eventuelle Fragen die du noch zu dem Gerät hast und klärt anschließend, ob ihr euch in der echten Welt trefft um das Gerät zu tauschen, oder ob ihr es irgendwie über den Postweg abwickelt. Wenn es um einen Verleih geht, solltet ihr auf jeden Fall klären was bei dem Gerät zu beachten ist - in jedem Fall sollte geklärt sein, dass es vor und nach dem Verleih komplett neu installiert wird. Ihr könnt auch weitere Kontaktinformationen austauschen und auf anderem Weg als per Mail kommunizieren.
</div>
<div class="row">
	<div class="span6">
<form action="{% url hardware.views.sendMail hardware.id %}" method="post" class="form">{% csrf_token %}
	<div class="control-group">
		<label class="control-label" for="id_text">Text, der dem/der Besitzer*in Mitgeteilt werden soll</label>
		<div class="controls">
			{{ form.text}}
			<span class="help-inline">{{form.text.errors}}</span>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_text">Beschreibe bitte kurz wofür du die Hardware brauchst</label>
		<div class="controls">
			{{ form.usage}}
			<span class="help-inline">{{form.usage.errors}}</span>
		</div>
	</div>
<a href="{% url hardware.views.displayHardware hardware.id hardare.slug %}"  class="btn btn-normal">Abbrechen</a>
<input type="submit" value="Submit" class="btn btn-primary" />
</form>
</div>
<div class="span6">
	<h4>Informationen zur Hardware</h4>
		<table class="table table-condensed">
			<tr><th>Bezeichnung</th><td>{{hardware.name}}</td><tr>
			<tr><th>Besitzer*in</th><td>{{hardware.owner}}</td><tr>
			<tr><th>Zustand</th><td>{{hardware.condition}}</td><tr>
			<tr><th>Art</th><td>{{hardware.state}}</td><tr>
		{% if hardware.lendlength != None %}<tr><th>Verleihdauer</th><td>{{hardware.lendlength}} {{lendlengthtype}}</td><tr>{% endif %}
            <tr><th>Gerätetyp</th><td><img src="/images/{{hardware.category.icon}}" />{{hardware.category}}</td><tr>
			{% if distance %}
			<tr><th>Entfernung</th><td>{{distance}}</td><tr>
			{% endif%}
		</table>
	<h5>Beschreibungstext</h5>
	<p>{{hardware.description}}</p>
</div>
</div>
{% endif %}
</div>
{% endblock %}