hfa/urls.py
# coding: utf-8 f
from django.conf.urls import patterns, include, url
from main.views import home, hardwareAbuse
from users.views import error, login, profile, settings, confirmEmail, newEmail, disconnect
from django.contrib import admin
from hardware.views import displayHardware, listHardware, listComponents, hardwareEdit, deleteHardware, sendMail, searchHardware, giveaway, takeback, new_images, history
from hfa.settings import DEBUG, MEDIA_ROOT
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
import allauth
from django.utils import importlib

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
 url(r'^upload/', include('fileupload.urls')),
    url(r'^$', home, name='home'),
    url(r'^users/(?P<userid>.*)$', profile, name='profile'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^hardware/view/(?P<id>.*)/(?P<name>.*)$', displayHardware, name="display hardware"),
    url(r'^hardware/giveaway/$', giveaway),
    url(r'^hardware/takeback/(?P<hardwareid>.*)', takeback),
    url(r'^hardware/new/$', hardwareEdit),
    url(r'^hardware/newimages/(?P<hardwareid>.*)$', new_images),
    url(r'^hardware/history/$', history),
    url(r'^hardware/edit/(?P<id>.*)$', hardwareEdit),
    url(r'^hardware/delete/(?P<id>.*)$', deleteHardware),
    url(r'^hardware/contact/(?P<hardwareid>.*)$', sendMail),
    url(r'^hardware/search/$', searchHardware),
    url(r'^hardware/search/(?P<page>.*)$', searchHardware),
    url(r'^hardware/list/$', listHardware),
    url(r'^hardware/list/components/$', listComponents),
    url(r'^hardware/list/components/(?P<page>\d*)$', listComponents),
    url(r'^hardware/list/(?P<page>\d*)$', listHardware),
    url(r'^hardware/abuse/$', hardwareAbuse),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login),
    url(r'^account/login/cancelled/$', "allauth.socialaccount.views.login_cancelled", name='socialaccount_login_cancelled'),
    url(r'^account/login/error/$', "allauth.socialaccount.views.login_error", name='socialaccount_login_error'),
    url(r"^logout/$", "allauth.account.views.logout", name="account_logout"),
    url(r'^accounts/confirm/(?P<confirmation_key>.*)$', confirmEmail),
    url(r'^accounts/newmail$', newEmail),
    url(r'^accounts/disconnect/(?P<socialacc>.*)$', disconnect),
    url(r'^accounts/delete/$', disconnect),
    url(r'^accounts/', include('allauth.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

for provider in allauth.socialaccount.providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += patterns('', url(r'^accounts/', include(prov_urlpatterns)))

if DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^images/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': MEDIA_ROOT}))

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from main.models import Location
from sorl.thumbnail import ImageField
from hfa.util import get_afile_name
from hardware.models import Hardware

class UserProfile(models.Model):
	# This field is required.
	user = models.OneToOneField(User)

	location = models.ForeignKey(Location, null=True)
	displayLocation = models.BooleanField(_('display location'), default=False)

	displayname = models.CharField(max_length=50, blank=False)

	confirmation_key = models.CharField(max_length=40, blank=True, null=True)
	key_expires = models.DateTimeField(blank=True, null=True)
	mail_confirmed = models.BooleanField(default=False)

	def delete(self, *args, **kwargs):
		hardware = Hardware.objects.filter(owner=self.user)
		hardware.delete()
		if self.location != None:
			self.location.delete()
		# Delete the model before the file
		super(UserProfile, self).delete(*args, **kwargs)

def create_user_profile(sender, instance, created, **kwargs):
	if created:
		UserProfile.objects.create(user=instance, displayname=instance.username)

post_save.connect(create_user_profile, sender=User)

users/forms.py
 # -*- coding: utf-8 -*-
from django import forms
from django.core import validators
from django.contrib.auth.models import User

def isValidUsername(field_data):
		try:
			User.objects.get(username=field_data)
		except User.DoesNotExist:
			return
		raise validators.ValidationError('Der Benutzername {} ist bereits vergeben.'.format(field_data))

class LocationForm(forms.Form):
	city = forms.CharField(max_length=200, required=False)
	street = forms.CharField(max_length=200, required=False)
	postcode = forms.CharField(max_length=5, required=False)
	displayLocation = forms.BooleanField(required=False)
	error_css_class = 'error'

class UserSettingsForm(forms.Form):
	displayname = forms.CharField(max_length=50, required=True)
	email = forms.EmailField(required=True)
	error_css_class = 'error'


class EmailForm(forms.Form):
	email = forms.EmailField(required=True)
	error_css_class = 'error'
	

users/views.py
 # -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.contrib.messages.api import get_messages
from django.contrib.auth.models import User
from hardware.models import Hardware
from allauth.socialaccount.models import SocialAccount, SocialApp
from geopy import geocoders
from users.forms import EmailForm, LocationForm, UserSettingsForm
from django.core.urlresolvers import reverse
from main.models import Location
from main.views import home
from users.models import UserProfile
from sorl.thumbnail import get_thumbnail
from hfa.util import create_map
import datetime, random, sha
from django.core.mail import send_mail
from django.contrib import messages
from allauth.account.forms import LoginForm, SignupForm, SetPasswordForm, ChangePasswordForm
def set_mail(user, email):
	if email != "":
		profile = user.get_profile()
		# Build the activation key for their account
		salt = sha.new(str(random.random())).hexdigest()[:5]
		confirmation_key = sha.new(salt+user.username).hexdigest()
		key_expires = datetime.datetime.today() + datetime.timedelta(2)



		profile.confirmation_key = confirmation_key
		profile.key_expires = key_expires
		profile.mail_confirmed = False
		profile.save()
		user.email = email
		user.save()
		# Send an email with the confirmation link

		email_subject = 'Your new hardware-fuer-alle.de email confirmation'
		email_body = """Hallo, {}, um deine E-Mail Adresse bei hardware-fuer-alle.de einzutragen musst du sie noch bestätigen\n
		Bitte klicke hierfür innerhalb der nächsten 48 Stunden auf diesen Link:\n\nhttp://hardware-fuer-alle.de/accounts/confirm/{}""".format(
			user.username,
			profile.confirmation_key)
		send_mail(email_subject,
				email_body,
				'support@hardware-fuer-alle.de',
				[user.email])

def error(request):
	"""Error view"""
	messages = get_messages(request)
	return render_to_response('error.html', {'messages': messages, },
		RequestContext(request))

def login(request,  **kwargs):
	success_url = kwargs.pop("success_url", None)

	if success_url is None:
		success_url = "/"

	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			return form.login(request, redirect_url=success_url)
	else:
		form = LoginForm()

	registerform = SignupForm()

	ctx = {
		"form": form,
		"registerform":registerform,
		"redirect_field_name": "next",
		"redirect_field_value": request.REQUEST.get("next"),
		"apps":SocialApp.objects.all(),
	}
	return render_to_response('users/login.html', RequestContext(request, ctx))

def profile(request, userid):
	"""displays a user profile"""
	user = get_object_or_404(User, id = userid)
	available_hardware =Hardware.objects.filter(owner=user, availability=True)
	
	accounts = SocialAccount.objects.filter(user=user)
	accountlist = []
	for account in accounts:
		accountlist.append(account)
	if user.get_profile().displayLocation:
		map, showmap = create_map(user.get_profile().location)
	else:
		map = None
	context = {
		'userprofile':user,
		'available_hardware':available_hardware,
		'map':map,
		'accountlist':accountlist}
	if request.user == user:
		unavailable_hardware =Hardware.objects.filter(owner=user, availability=False)
		context['unavailable_hardware'] = unavailable_hardware
	return render_to_response('users/userprofile.html', context, RequestContext(request))

@login_required
def settings(request):
	"""displays the settings for an account"""
	user = request.user
	profile = user.get_profile()
	accounts = SocialAccount.objects.filter(user=user)
	accountlist = []
	for account in accounts:
		accountlist.append(account.provider)
	apps = SocialApp.objects.all()
	context = {}
	if request.method == 'POST': # If the form has been submitted...
		if request.POST["type"] == "location":
			lform = LocationForm(request.POST)
			mform = UserSettingsForm()
			if lform.is_valid(): # All validation rules pass
				if profile.location==None:
					location = Location()
					location.save()
					profile.location = location
					profile.save()
				else:
					location = profile.location
				location.city = lform.cleaned_data['city']
				location.street = lform.cleaned_data['street']
				location.postcode = lform.cleaned_data['postcode']
				profile.displayLocation = lform.cleaned_data['displayLocation']
				g = geocoders.Google()
				if location.city!= "" or location.street!="" or location.street!="":
					try:
						places = g.geocode(location.street + ", " + location.postcode + " " + location.city, exactly_one=False)
						location.latitude = places[0][1][0]
						location.longitude = places[0][1][1]
						location.save()
					except geocoders.google.GQueryError, e:
						messages.add_message(request, messages.ERROR, u"Es konnte kein Ort gefunden werden, der deiner Eingabe entspricht. Hast du dich vielleicht vertippt?")
				else:
					location.latitude = None
					location.longitude = None
					location.save()
				profile.save()
		else:
			lform = LocationForm()
			mform = UserSettingsForm(request.POST)
			mform.user = request.user
			if mform.is_valid():
				if mform.cleaned_data['email'] != user.email:
					set_mail(user, mform.cleaned_data['email'])
				if mform.cleaned_data['displayname'] != profile.displayname:
					profile.displayname = mform.cleaned_data['displayname']
					profile.save()
				user.save()
	else:
		lform = LocationForm()
		mform = UserSettingsForm()
	if user.password != "":
		passform = ChangePasswordForm()
	else:
		passform = SetPasswordForm()
	context.update({"apps":apps, "accountlist":accountlist, 'profile':profile, 'lform':lform, 'mform':mform, 'passform':passform})
	map, showmap = create_map(profile.location)
	context["map"] = map
	context["showmap"] = showmap
	return render_to_response('users/usersettings.html', context, RequestContext(request))

@login_required
def confirmEmail(request, confirmation_key):
	profile = request.user.get_profile()
	if profile.confirmation_key==confirmation_key:
		#if profile.key_expires < datetime.datetime.today():
		#	return render_to_response('users/confirm.html', {'expired': True}, RequestContext(request))
		profile.mail_confirmed = True
		profile.save()
		return render_to_response('users/confirm.html', {'success': True}, RequestContext(request))
	else:
		return render_to_response('users/confirm.html', {'invalid': True}, RequestContext(request))

@login_required
def newEmail(request):
	user = request.user
	profile = user.get_profile()
	if request.POST:
		form = EmailForm(request.POST)
		form.user = request.user
		if form.is_valid():
			set_mail(user, form.cleaned_data["email"])
			return render_to_response('users/newmail.html', {'set': True}, RequestContext(request))
	else:
		form = EmailForm()
		if not profile.mail_confirmed and user.email != "":
			return render_to_response('users/newmail.html', {'unfinished': True}, RequestContext(request))
	return render_to_response('users/newmail.html', {'form': form}, RequestContext(request))

@login_required
def disconnect(request, socialacc=False):
	accounts = SocialAccount.objects.filter(user=request.user)
	if request.POST and socialacc == False:
		request.user.get_profile().delete()
		request.user.delete()
		return HttpResponseRedirect(reverse(home))
	if len(accounts) == 1:
		return render_to_response('users/deleteaccount.html', {}, RequestContext(request))
	account = accounts.filter(provider=socialacc)
	account.delete()	
	
	messages.add_message(request, messages.SUCCESS, u"Die Verknüpfung wurde aufgehoben.")
	return HttpResponseRedirect(reverse(settings))

templates/users/confirm.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}

{% block heading %}
Email-Bestätigung
{% endblock %}


{% block content %}
<div class="span12">
{% if success %}
	<p>Deine Emailadresse wurde bestätigt!</p>
{% elif expired %}
	<p>Dein Bestätigungscode ist abgelaufen... sollen wir dir einen Neuen senden oder möchtest du die Emailadresse ändern?</p>
{% else %}
	<p>Dein Bestätigungscode ist ungültig. Sollen wir dir einen Neuen senden oder möchtest du deine Emailadresse ändern?</p>
{% endif %}
</div>
{% endblock %}

templates/users/deleteaccount.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}

{% block heading %}
Account wirklich löschen?
{% endblock %}


{% block content %}
<div class="span12">
<div class="alert alert-error">
Dies ist die letzte bestehende Verknüpfung. Wenn du sie löschst, wird dein kompletter Account bei Hardware für Alle gelöscht.
Sicher das du das tun möchtest?
</div>
<form action="{% url users.views.disconnect %}" method="post" class="form-inline">{% csrf_token %}
		
<a href="{% url users.views.settings %}" class="btn">Nein, doch nicht</a><button type="submit" class="btn btn-danger">Ja, ich bin sicher</button>
</form>
</div>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% load socialaccount %}

{% block heading %}
Anmelden
{% endblock %}


{% block content %}
<div class="span12">
{% for app in apps %}
	<a href="{% provider_login_url app.provider %}" class="btn btn-success">Mit {{app.provider}} anmelden</a>
{% endfor %}


<div class="row">
	<div class="span6">
		<h3>Mit Passwort anmelden</h3>
<form method="post" action="{% url allauth.account.views.login %}" class="form-horizontal">
{{form.non_field_errors}}
{% csrf_token %}
 <div class="control-group">
<label class="control-label" for="id_login">E-Mail Adresse</label>
<div class="controls">
{{form.login}}{{form.login.errors}}
</div></div>
 <div class="control-group">
<label class="control-label" for="id_password">Passwort</label>
<div class="controls">
{{form.password}}{{form.password.errors}}
</div></div>

<input type="submit" value="Einloggen" class="btn btn-primary" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
<a href="{% url allauth.account.views.password_reset%}">Passwort vergessen</a>
</div>


<div class="span6">
	<h3>Neu registrieren</h3>
<form method="post" action="{% url allauth.account.views.signup %}" class="form-horizontal">
{{registerform.non_field_errors}}
{% csrf_token %}
 <div class="control-group">
<label class="control-label" for="id_login">Benutzername</label>
<div class="controls">
{{registerform.username}}{{registerform.username.errors}}
</div></div>
 <div class="control-group">
<label class="control-label" for="id_login">E-Mail Adresse</label>
<div class="controls">
{{registerform.email}}{{registerform.email.errors}}
</div></div>
 <div class="control-group">
<label class="control-label" for="id_password1">Passwort</label>
<div class="controls">
{{registerform.password1}}{{registerform.password1.errors}}
</div></div>
 <div class="control-group" id="passwordrepeat">
<label class="control-label" for="id_password2">Passwort wiederholen</label>
<div class="controls">
{{registerform.password2}}{{registerform.password2.errors}}
</div></div>

<input type="submit" value="Registrieren" class="btn btn-primary" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
</div>
</div>
</div>
{% endblock %}

templates/users/newmail.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}

{% block heading %}
Neue E-Mail-Adresse
{% endblock %}


{% block content %}
<div class="span12">
{% if set %}
	<p>Wir haben eine Email mit dem Bestätigungslink an {{user.email}} gesendet. Bitte folge den Anweisungen in der Email und bestätige die Adresse innerhalb von 48 Stunden.</p>
{% elif unfinished %}
	<p>Wir haben dir bereits einen Bestätigungscode geschickt. Bitte benutze zuerst diesen.</p>
{% else %}
	<form action="{% url users.views.newEmail %}" method="post" class="form-horizontal">{% csrf_token %}
	<div class="control-group">
		<label class="control-label {{form.email.css_classes}}" for="id_email">E-Mail-Adresse</label>
		<div class="controls">
			 {{form.email}}
			<span class="help-inline">{{form.email.errors}}</span>
		</div>
	</div>
		<button type="submit" class="btn btn-primary">E-Mail-Adresse setzen</button>
</form>
{% endif %}
</div>
{% endblock %}

templates/users/usersettings.html
{% extends "base.html" %}

{% load socialaccount %}
{% load i18n %}
{% load thumbnail %}
{% load gravatar %}

{% block heading %}
Profil bearbeiten
{% endblock %}

{% block script %}
function checkStreet() {
	if ($("#id_city").val() || $("#id_postcode").val()) {
		$("#id_street").prop('disabled', false);
	} else {
		$("#id_street").val("");
		$("#id_street").prop('disabled', true);
	}
}


checkStreet()
$(function() {
	$("#id_city").keypress(function() {checkStreet()});
	$("#id_postcode").keypress(function() {checkStreet()});
	$("#id_city").change(function() {checkStreet()});
	$("#id_postcode").change(function() {checkStreet()});

	$( "#id_city" ).autocomplete({
		source: function( request, response ) {
			$.ajax({
				url: "http://ws.geonames.org/searchJSON",
				dataType: "jsonp",
				data: {
					featureClass: "P",
					style: "full",
					maxRows: 12,
					country: "DE",
					lang:"de",
					name_startsWith: request.term
				},
				success: function( data ) {
					response( $.map( data.geonames, function( item ) {
						return {
							label: item.name + (item.adminName1 ? ", " + item.adminName1 : ""),
							value: item.name,
							postcode: item.lat
						}
					}));
				}
			});
		},
		minLength: 2,
		select: function( event, ui ) {
			 checkStreet();
		},
		open: function() {
			$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
		},
		close: function() {
			$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
		}
	});
});
{% endblock %}

{% block content %}
	<div class="span6">

	<h3>Verbindungen</h3>
	<p>Wenn du Verbindungen zu anderen Seiten herstellst, kannst du dich mit diesen Profilen hier anmelden.</p>
	{% for app in apps %}
		<p>
		{% if app.provider in accountlist %}
			<a href="{% url users.views.disconnect app.provider %}" class="btn btn-danger">Entferne Verbindung zu {{app.provider}}</a>
		{% else %}
			<a href="{% provider_login_url app.provider %}" class="btn btn-success">Verbinde dein Profil mit {{app.provider}}</a>
		{% endif %}
		</p>
	{% endfor %}

	<h3>Profil</h3>
	<form action="{% url users.views.settings %}" method="post" class="form-inline">{% csrf_token %}
		<div class="control-group {{mform.displayname.css_classes}}">
		<label class="control-label" for="id_displayname">Anzeigename</label>
		<div class="controls">
			<input id="id_displayname" type="text" name="displayname" maxlength="200" value="{{ profile.displayname }}"/>
			<span class="help-inline">{{mform.displayname.errors}}</span>
		</div>
		</div>

	<h3>E-Mail-Adresse</h3>
	<p>Trage eine E-Mail-Adresse ein, damit du Benachrichtigungen über Leihanfragen erhalten kannst.</p>
		<div class="control-group {{mform.email.css_classes}}">
		<div class="controls">
			<input id="id_email" type="text" name="email" maxlength="200" value="{{user.email}}"/>
		<span class="help-inline">{{mform.email.errors}}</span>
		<span>{{mailconfirm}}</span>
		</div>
		</div>
		<input type="hidden" name="type" value="main">
		<p><button type="submit" class="btn btn-primary">Speichern</button></p>
	</form>

	
	{% if user.password != "" %}
	<h3>Passwort ändern</h3>
	<form action="{% url allauth.account.views.password_change %}" method="post" class="form-inline">{% csrf_token %}
	 	<div class="control-group">
		<label class="control-label" for="id_oldpassword">altes Passwort</label>
		<div class="controls">
		{{passform.oldpassword}}{{passform.oldpassword1errors}}
		</div></div>
		 <div class="control-group">
		<label class="control-label" for="id_password1">neues Passwort</label>
		<div class="controls">
		{{passform.password1}}{{passform.password1.errors}}
		</div></div>
		 <div class="control-group" id="passwordrepeat">
		<label class="control-label" for="id_password2">neues Passwort wiederholen</label>
		<div class="controls">
		{{passform.password2}}{{passform.password2.errors}}
		</div></div>
		<p><button type="submit" class="btn btn-primary">Ändern</button></p>
	</form>
	{% else %}
		<h3>Passwort setzen</h3>
		<form action="{% url allauth.account.views.password_set %}" method="post" class="form-inline">{% csrf_token %}
		 <div class="control-group">
		<label class="control-label" for="id_password1">Passwort</label>
		<div class="controls">
		{{passform.password1}}{{passform.password1.errors}}
		</div></div>
		 <div class="control-group" id="passwordrepeat">
		<label class="control-label" for="id_password2">Passwort wiederholen</label>
		<div class="controls">
		{{passform.password2}}{{passform.password2.errors}}
		</div></div>
		<p><button type="submit" class="btn btn-primary">Setzen</button></p>
	{% endif %}

	<h3>Avatar</h3>
	<p>Dein Avatar wird über den Dienst Gravatar gesetzt. Deine Mail-Adresse, die du hier hinterlegt hast bestimmt welches Bild von Gravatar abgerufen wird. Ein Avatarbild kannst du <a href="https://de.gravatar.com/" target="_blank">hier</a> ändern/setzen.</p>
	{% if user.get_profile.mail_confirmed %}
	    	<img src="{% gravatar_url user.email 250 %}" class="img-polaroid">
	    	{% else %}
	    	<img src="{% gravatar_url "" 250 %}" class="img-polaroid">
	    	{% endif %}
	</div>
	<div class="span6">

	<h3>Standort</h3>
<form action="{% url users.views.settings %}" method="post" class="form-inline">{% csrf_token %}
	<div class="control-group {{lform.city.css_classes}}">
		<label class="control-label" for="id_city">Stadt</label>
		<div class="controls">
			<input id="id_city" type="text" name="city" maxlength="200" value="{{ profile.location.city }}"/>
			<span class="help-inline">{{lform.city.errors}}</span>
		</div>
	</div>
	<div class="control-group {{lform.postcode.css_classes}}">
		<label class="control-label" for="id_postcode">Postleitzahl</label>
		<div class="controls">
			<input id="id_postcode" type="text" name="postcode" maxlength="5" value="{{ profile.location.postcode }}"/>
			<span class="help-inline">{{lform.postcode.errors}}</span>
		</div>
	</div>
	<div class="control-group {{lform.street.css_classes}}">
		<label class="control-label" for="id_street">Straße</label>
		<div class="controls">
			<input id="id_street" type="text" name="street" maxlength="200" value="{{ profile.location.street }}"/>
			<span class="help-inline">{{lform.street.errors}}</span>
		</div>
	</div>
	<div class="control-group {{lform.displaylocation.css_classes}}">

		<div class="controls">
			{% if profile.displayLocation %}
				<input type="checkbox" name="displayLocation" id="id_displayLocation" checked/>
			{% else %}
				<input type="checkbox" name="displayLocation" id="id_displayLocation"/>
			{% endif %}
			<span>Ort im meinem öffentlichen Profil anzeigen</span>
			<span class="help-inline">{{lform.displayLocation.errors}}</span>
		</div>
	</div>
		<input type="hidden" name="type" value="location">
		<button type="submit" class="btn btn-primary">Save changes</button>
</form>

{% if showmap %}
	{{ map.map }}
{% endif %}

	</div>
{% endblock %}